/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.ini4j.Ini;
import org.ini4j.Profile.Section;
import org.junit.Test;

import java.io.*;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class Ini4JTest {
    @Test
    public void testCreatingIniFilesWithGroups() throws Exception {
        final Ini ini = new Ini();
        final Section section = ini.add("default");

        section.add("list", "value 1", 0);
        section.add("list", "value 2", 1);
        section.add("list", "value 3", 2);
        section.add("list", "value 4", 3);

        final OutputStream stream = new ByteArrayOutputStream();
        ini.store(stream);
        final String actual = stream.toString();

        assertThat(actual).contains("[default]\nlist = value 1\nlist = value 2\nlist = value 3\nlist = value 4");
    }

    @Test
    public void testReadIniFileWithGroups() throws Exception {
        final String iniContents = "[default]\n" +
                "list = value 1\n" +
                "list = value 2\n" +
                "list = value 3\n" +
                "list = value 4\n";

        final InputStream stream = new ByteArrayInputStream(iniContents.getBytes());

        final List<String> actual = new Ini(stream).get("default").getAll("list");

        assertThat(actual).isEqualTo(Arrays.asList("value 1", "value 2", "value 3", "value 4"));
    }
}
